site_name: Procedures and Practices

# Git repository
repo_url: https://github.com/ACCESS-NRI/Procedures-and-Practices
repo_name: Procedures and Practices
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - scheme: light
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  logo: assets/ACCESSLogoJustPlanet.png

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: index.md
  - Technical: 
    - Code and Workflow Management: technical/code_and_workflow_platform_strategy.md
    - Documentation Platform:  technical/documentation_platform_strategy.md
    - Forum and Discussion Platform: technical/forum_and_discussion_platform.md
    - Reproducibility and Performance Testing: technical/reproducibility_and_performance_testing_organisation.md
  - Release Management: 
    - Release Specification: release/release_specification.md
    - Licensing: release/licensing.md