site_name: Procedures and Practices

# Git repository
repo_url: https://github.com/ACCESS-NRI/Procedures-and-Practices
repo_name: Procedures and Practices
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  logo: assets/ACCESSLogoJustPlanet.png

# Footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel

copyright: Copyright &copy; 2022 - ACCESS-NRI

extra_css:
  - css/fontello.css

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: 
    - index.md
    - License: LICENSE.md
  - Technical: 
    - Code and Workflow Management: technical/code_and_workflow_platform_strategy.md
    - Documentation Platform:  technical/documentation_platform_strategy.md
    - Forum and Discussion Platform: technical/forum_and_discussion_platform.md
    - Reproducibility and Performance Testing: technical/reproducibility_and_performance_testing_organisation.md
  - Release Management: 
    - Licensing: release/licensing.md
    - Release Specification: release/release_specification.md